/*
   This JavaScript code was generated by Jemplate, the JavaScript
   Template Toolkit. Any changes made to this file will be lost the next
   time the templates are compiled.

   Copyright 2006-2008 - Ingy döt Net - All rights reserved.
*/

if (typeof(Jemplate) == 'undefined')
    throw('Jemplate.js must be loaded before any Jemplate template files');

Jemplate.templateMap['input.html'] = function(context) {
    if (! context) throw('Jemplate function called without context\n');
    var stash = context.stash;
    var output = '';

    try {
output += '<form action="#" name="microformat" method=\'POST\'>\n    <label>Your Space Name:</label>\n    <input type="text" name="space_name"><br/>\n    <label>Your Longitude:</label>\n    <input type="text" name="longitude"><br/>\n    <label>Your Latitude:</label>\n    <input type="text" name="latitude"><br/>\n\n    <input type="submit" name="generate" value="Generate"><br/>\n</form>\n\n<div class="result" style="display:none">\n    <hr/>\n    <p>Copy this HTML into your web site</p>\n    <textarea rows="10" cols="40"></textarea>\n</div>\n';
    }
    catch(e) {
        var error = context.set_error(e, output);
        throw(error);
    }

    return output;
}

Jemplate.templateMap['microformat.html'] = function(context) {
    if (! context) throw('Jemplate function called without context\n');
    var stash = context.stash;
    var output = '';

    try {
output += '<!-- coworking directory -->\n<div class="coworking" style="display:none;">\n    <span class="space_name">';
//line 3 "microformat.html"
output += stash.get('space_name');
output += '</span>\n    <div class="geo">\n        <span class="latitude">';
//line 5 "microformat.html"
output += stash.get('longitude');
output += '</span>\n        <span class="longitude">';
//line 6 "microformat.html"
output += stash.get('latitude');
output += '</span>\n    </div>\n</div>\n';
    }
    catch(e) {
        var error = context.set_error(e, output);
        throw(error);
    }

    return output;
}

